myset = set()
myset.add('abc')
myset.add('abc')
myset.add('abc')
myset.add('abc')
myset.add('abc')
myset.add('abc')
myset.add('abc')
myset.add('abc')
myset.add('abc')
myset.add('abc')
myset.add('abc')
myset.add('abcdef')
myset.add('abc')
myset.add('abc')
myset.add('abc')
myset.add('abc')
print myset
